"""Add published_at to ArticleVersion

Revision ID: b5cb54d5e21f
Revises: 1c96f65903fb
Create Date: 2025-04-03 16:41:59.853509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cb54d5e21f'
down_revision: Union[str, None] = '1c96f65903fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_versions', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_versions', 'published_at')
    # ### end Alembic commands ###
